### ISSUE TITLE
crate does not re-export `bstr`, therefore requires users to add this dependency

### ISSUE THREAD

**Issue by pickx** [mathematic-inc/unfmt#12]
hey, on my machine this example

```rust
use unfmt::unformat;

fn main() {
    unformat!("hello", world);
}
```
in `Cargo.toml`:
```toml
[dependencies]
unfmt = { git = "https://github.com/mathematic-inc/unfmt.git" }
```

...results in
```
error[E0432]: unresolved import `bstr`
```

I believe this is because the macro expansion includes `use ::bstr::{ByteSlice, BStr};`.
this means a user would need to add `bstr` as a dependency - see [this Stack Overflow question](https://stackoverflow.com/questions/54593472/how-do-i-write-a-procedural-macro-that-expands-to-a-macro-invocation-without-req).

afaik, there are ways to deal with this, such as re-exporting.
